var texts_json = {};
texts_json['EN'] = {};
texts_json['DE'] = {};
texts_json['ES'] = {};
texts_json['FR'] = {};
texts_json['ID'] = {"Name":"Nama","Balance":"Saldo","Log_in":"Masuk","Please_select_a_value":"Silakan pilih nilai","Deposit_is_done__Transaction_ID:_[_1]":"Deposit selesai. ID transaksi: [_1]","Volatility_Indices":"Indeks Volatilitas"};
texts_json['IT'] = {};
texts_json['PL'] = {};
texts_json['PT'] = {};
texts_json['RU'] = {"Volatility_Indices_Account":"Счёт на индексах волатильности","Log_in":"Вход","Volatility_Indices":"Индексы волатильности","Name":"Имя","Balance":"Баланс","Demo":"Демо"};
texts_json['TH'] = {};
texts_json['VI'] = {};
texts_json['ZH_CN'] = {"Financial":"金融","Balance":"余额","Demo":"演示","Deposit_is_done__Transaction_ID:_[_1]":"已完成存款。交易编号: [_1]","Please_select_a_value":"请选择数值","Name":"姓名","Log_in":"登录","Please_contact_<a_href=\"[_1]\">Customer_Support</a>_":"请联系<a href=\"[_1]\">客服部</a>。"};
texts_json['ZH_TW'] = {"Please_contact_<a_href=\"[_1]\">Customer_Support</a>_":"請聯繫<a href=\"[_1]\">客服部</a>。","Log_in":"登入","Name":"姓名","Please_select_a_value":"請選擇數值","Deposit_is_done__Transaction_ID:_[_1]":"已完成存款。交易編號: [_1]","Balance":"餘額","Demo":"示範","Financial":"金融"};
texts_json['ACH'] = {};
